export const manufacturers = [
  "Abarth",
  "AC Cars",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "BYD",
  "Bentley",
  "Brabus",
  "Bugatti",
  "Buick",
  "Caterham",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Cupra",
  "Dacia",
  "Daihatsu",
  "Dodge",
  "DS Automobiles",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "GMC",
  "Genesis",
  "Great Wall Motors",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "MINI",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mahindra",
  "Morgan",
  "NIO",
  "Nissan",
  "Pagani",
  "Peugeot",
  "Pininfarina",
  "Porsche",
  "Proton",
  "Qoros",
  "Ram",
  "Renault",
  "Rivian",
  "Rolls-Royce",
  "Ruf",
  "SEAT",
  "Saab",
  "Scion",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "TVR",
  "Vauxhall",
  "Volkswagen",
  "Volvo",
  "Wiesmann",
  "Zenvo",
  ];
  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
    { title: "2024", value: "2024" },
  ];
  
  export const fuels = [
    { title: "Fuel", value: "", },
    { title: "Gas", value: "Gas", },
    { title: "Electricity", value: "Electricity", },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];